### ISSUE TITLE
Example graph does not work. 

### ISSUE THREAD

**Issue by ashea2nd** [kjahan/community#4]
Error returned is when I try to follow the example. 

Traceback (most recent call last):
  File "cmty.py", line 122, in <module>
    sys.exit(main(sys.argv))
  File "cmty.py", line 116, in main
    Orig_deg = UpdateDeg(A, G.nodes())
  File "cmty.py", line 64, in UpdateDeg
    n = len(nodes)  #len(A) ---> some ppl get issues when trying len() on sparse matrixes!
TypeError: object of type 'generator' has no len()

**Comment by canbax** [comment]
It's about your version of networkx. Use 1.10 version. [this version](https://networkx.github.io/documentation/networkx-1.10/reference/generated/networkx.Graph.nodes.html) returns a list. Some versions might return a generator which has no len()

**Comment by gbarm** [comment]
Hi, I got something similar I have version 2.0 of networkx 
 Traceback (most recent call last):
  File "/Users/gba/cmty.py", line 122, in <module>
    sys.exit(main(sys.argv))
  File "/Users/gba/cmty.py", line 116, in main
    Orig_deg = UpdateDeg(A, G.nodes())
  File "/Users/gba/cmty.py", line 67, in UpdateDeg
    deg_dict[nodes[i]] = B[i, 0]
TypeError: unhashable type: 'dict'
