### ISSUE TITLE
TypeError: unhashable type: 'dict'

### ISSUE THREAD

**Issue by SeekPoint** [kjahan/community#9]
mldl@ub1604:~/ub16_prj/community$ python cmty.py graph.txt
Traceback (most recent call last):
  File "cmty.py", line 122, in <module>
    sys.exit(main(sys.argv))
  File "cmty.py", line 116, in main
    Orig_deg = UpdateDeg(A, G.nodes())
  File "cmty.py", line 67, in UpdateDeg
    deg_dict[nodes[i]] = B[i, 0]
TypeError: unhashable type: 'dict'
mldl@ub1604:~/ub16_prj/community$

**Comment by tanxiaoyao** [comment]
cause you may use the newest version of networkx，I uninstall the networkx 2.1 and reinstall older version ,it works again.

pip uninstall networkx
pip install networkx==1.11

**Comment by tanxiaoyao** [comment]
@loveJasmine , Cause you may use the newest version of networkx，I uninstall the networkx 2.1 and reinstall older version ,it works again.

pip uninstall networkx
pip install networkx==1.11
